version = 1
platform = "github"
lang = "rust"

[[artifacts]]
type = "bin"
name = "enderpearl"
outputName = "{name}-{os}"

[[targets]]
id = "linux"
for = "enderpearl"
os = "linux"
arch = [ "x86_64" ]
abi = "musl"
packages = [ "bin" ]
type = "bin"

[[targets]]
id = "windows"
for = "enderpearl"
os = "windows"
arch = [ "x86_64" ]
abi = "msvc"
packages = [ "bin" ]
type = "bin"

[release]
strip = true
lto = true
codegenUnits = 1
panic = "abort"

[[publish]]
type = "builtin"
builtin = "download_artifact"

[[publish]]
type = "builtin"
builtin = "github_release"

[[publish]]
type = "composite"
name = "Publish Docker to GHCR"
action = "docker-publish"
with = { image_name = "sircesarium/enderpearl" }
permissions = { packages = "write" }

# [[publish]]
# type = "composite"
# name = "Publish to Crates.io"
# action = "cargo-publish"
# secrets = ["CRATES_TOKEN"]
